version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_USER: root
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - finance-u:/var/lib/postgresql/data

volumes:
  finance-u:
    external: false
